CREATE TABLE IF NOT EXISTS books(
    bookId BIGINT NOT NULL AUTO_INCREMENT,
    bookName VARCHAR(100) NOT NULL UNIQUE,
    bookAuthor VARCHAR(45) NOT NULL,
    releaseDate TIMESTAMP NOT NULL,
    PRIMARY KEY(bookId)
);