CREATE TABLE IF NOT EXISTS books(
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL UNIQUE,
    author VARCHAR(45) NOT NULL,
    releaseDate TIMESTAMP NOT NULL,
    PRIMARY KEY(bookId)
);